apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "team-management.configmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team-management.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  MEILI_NO_ANALYTICS: "true"
  AUTH_URL: {{ .Values.app.authUrl | quote }}
  # Meilisearch is reached via K8s internal DNS: <release>-meilisearch.<namespace>.svc.cluster.local
  MEILISEARCH_HOST: "http://{{ include "team-management.fullname" . }}-meilisearch:7700"
